### ISSUE TITLE
invalid: unexpected pubkey size

### ISSUE THREAD

**Issue by eko2one** [swentel/nostr-php#10]
There seems to be a problem with the public key length. They should be of 64 length but are 66.
Any idea what this could be related to?

Cannot publish to relays, since they return: invalid: unexpected pubkey size

**Comment by eko2one** [comment]
Seems like there is a prefix, when compressed pubkey is derived https://github.com/simplito/elliptic-php/issues/4#issuecomment-391512728

We need to strip first two characters.

**Comment by swentel** [comment]
merged, thanks!
