### ISSUE TITLE
New method to verify nostr events

### ISSUE THREAD

**Issue by quentintaranpino** [swentel/nostr-php#17]
Create a new method to verify if a nostr event is well formed and also of course well signed.

**Comment by quentintaranpino** [comment]
Ok, thank you!

**Comment by Sebastix** [comment]
For work later on how it's done on other libs:

https://github.com/nbd-wtf/nostr-tools/blob/5539e5cf896d7aad0849e2ac8b002def6f513750/event.ts#L81
https://github.com/ethicnology/dart-nostr/blob/develop/lib/src/event.dart#L328

**Comment by quentintaranpino** [comment]
Another resource, it will be compatible? 

https://github.com/kornrunner/php-secp256k1

**Comment by quentintaranpino** [comment]
More information, I've tried to integrate it myself but I don't have enough experience with this. 

https://github.com/phpecc/phpecc/blob/master/examples/verify_signature.php
