### ISSUE TITLE
It seems that it's not needed to close the connection in the function `send()`

### ISSUE THREAD

**Issue by georgkaser** [swentel/nostr-php#28]
It seems that it's not needed to close the connection in the function `send()`: After commenting `$client->close();` it works fine with no exception. Is the connection closing automatically?

_Originally posted by @georgkaser in https://github.com/swentel/nostr-php/issues/26#issuecomment-1498684799_

**Comment by swentel** [comment]
Hmm, weird, I've not encountered that issue yet when testing myself.

We'll have to read up on the client library.

(note: I'm on holiday until the 17th, so a bit slow at the moment)

**Comment by georgkaser** [comment]
No problem, hav a nice holiday. I will try to implement your classes into an REDAXO CMS Addon. Will also need time, because I will do it in my free time. I will keep you updated :)

**Comment by Sebastix** [comment]
Fixed in https://github.com/swentel/nostr-php/pull/46
