### ISSUE TITLE
thx for coding this

### ISSUE THREAD

**Issue by mega7mega** [swentel/nostr-php#3]
thx for coding this btw, 
i dont use drupal but i used your code to publish posts through php on nostr :-)

could you add something like create new keypair with all 4 options: npub, nsec, and their hex versions?
i am a noob to nostr programming :-D

**Comment by swentel** [comment]
Generating should be easy - at least I think so :)

Converting from hex to bech32 happens in #2 - I've split off the generating in #4

**Comment by swentel** [comment]
@mega7mega generating keys is in!

**Comment by mega7mega** [comment]
awesome thank you :-D i am planning to launch a youtube "competitor" on a small scale.. just MVP :-) got ontube.org today.
will use some of those functions :-D
