### ISSUE TITLE
$signer->signEvent is breaking the script but returns no error

### ISSUE THREAD

**Issue by pedromvpg** [swentel/nostr-php#33]
For some reason the line   **$signer->signEvent($note, "nsec1s3ul24jggks7fn2...5u6ph3flgxdjkcsl5tc7q");** is stopping the script but I can't see any error.

Here's the code I'm running.

```
require __DIR__.'/vendor/autoload.php';

use swentel\nostr\Event\Event;
use swentel\nostr\Message\EventMessage;
use swentel\nostr\Relay\Relay;
use swentel\nostr\Sign\Sign;


ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);


function send($message) {
  $note = new Event();
  $note->setContent($message)->setKind(1);
  print_r($note);  
  $signer = new Sign();
  
  /* The line below breaks the script and retruns no error */
  $signer->signEvent($note, "nsec1s3ul24jggks7fn2...5u6ph3flgxdjkcsl5tc7q");
 
  $eventMessage = new EventMessage($note);
  $websocket = 'wss://eden.nostr.land';
  $relay = new Relay($websocket, $eventMessage);
  $result = $relay->send();
  
  if ($result->isSuccess()) {
    print "Sent to Nostr!\n";
  } else {
    print 'Something went wrong: ' . $result->message() . "\n";
  }
  
}

$message = 'Hello World';
send($message);
```

**Comment by Sebastix** [comment]
`$signer->signEvent($note, "nsec1s3ul24jggks7fn2...5u6ph3flgxdjkcsl5tc7q");`

Looks like the second argument (`nsec1s3ul24jggks7fn2...5u6ph3flgxdjkcsl5tc7q`) in `signEvent` is not a valid private key string. 
You could try `nsec1vl029mgpspedva04g90vltkh6fvh240zqtv9k0t9af8935ke9laqsnlfe5`  which can be found in one the tests.

**Comment by pedromvpg** [comment]
Thanks,
the private key was not valide because I replaced some of the characters with "...".
Tried with the sample one provided from other tests and returns the same result.

Does it work for you?

**Comment by Sebastix** [comment]
A quick test: https://play.phpsandbox.io/swentel/nostr-php/VBgz6pXzOm5kdnvN

```Exception with message 'Invalid characters'
   null```

**Comment by Sebastix** [comment]
@pedromvpg Have you tried it with private key in hex value? I just found out that the code is expecting a private key in hex and doesn't convert your nsec to hex when the event is signed.

**Comment by Sebastix** [comment]
Fix in https://github.com/swentel/nostr-php/pull/38
