### ISSUE TITLE
Add php installation requirements

### ISSUE THREAD

**Issue by eko2one** [swentel/nostr-php#7]
What was missing in my case
- php8.x-gmp
- php8.x-xml

**Comment by Sebastix** [comment]
Did you install the library as a package with composer?

**Comment by eko2one** [comment]
no I cloned the repo and run `composer install`.
php8.0
phpunit 9^

**Comment by eko2one** [comment]
I am getting strange notice when running tests:

    PHPUnit 9.6.4 by Sebastian Bergmann and contributors.

       Warning - The configuration file did not pass validation!
      The following problems have been detected:

      Line 2:
      - Element 'phpunit', attribute 'cacheDirectory': The attribute 'cacheDirectory' is not allowed.

      Test results may not be as expected.

**Comment by swentel** [comment]
Hmm interesting, I have PHPUnit 10.0.12 and PHP 8.1 locally.
Can't tell if that's the cause of the problem though.

**Comment by eko2one** [comment]
Ok just saw that `cacheDirectory` is an attribute in phpunit10.Will switch to php8.1 and phpunit10.

**Comment by eko2one** [comment]
PHPUnit 10.0.14 by Sebastian Bergmann and contributors.

    Runtime:       PHP 8.1.16
    Configuration: ../nostr-php/phpunit.xml.dist

    ..                                                                  2 / 2 (100%)

    Time: 00:00.004, Memory: 6.00 MB

Requirements:
PHP 8.1
phpunit 10^

**Comment by swentel** [comment]
Does phpunit require 8.1 ? If so, we only need to set a version in require-dev for phpunit

OTOH, php8.0 is already in security modus, so might not be a big problem to up that too.

**Comment by eko2one** [comment]
phpunit10 requires php81 afaik

**Comment by swentel** [comment]
This should be good right?

    diff --git a/composer.json b/composer.json
    index eff07a3..5c9f31f 100644
    --- a/composer.json
    +++ b/composer.json  
    @@ -4,13 +4,14 @@
         "homepage": "https://github.com/swentel/nostr-php",
         "license": "GPL-2.0-or-later",
         "require": {
    -        "php": ">=8.0",
    +        "php": "^8.1",
             "ext-gmp": "*",
    +        "ext-xml": "*",
             "public-square/phpecc": "^0.1.0",
             "bitwasp/bech32": "^0.0.1"
         },
         "require-dev": {
    -        "phpunit/phpunit": "*"
    +        "phpunit/phpunit": "^10"
         },
         "autoload": {
             "psr-4": {

**Comment by eko2one** [comment]
tiptop

**Comment by swentel** [comment]
Alright, done!
